-- 채팅 이미지 테이블 생성
CREATE TABLE CHAT_IMAGE (
    CHAT_IMAGE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MESSAGE_ID BIGINT NOT NULL,
    IMAGE_URL VARCHAR(500) NOT NULL,
    ORIGINAL_NAME VARCHAR(255) NOT NULL,
    FILE_SIZE BIGINT,
    CONTENT_TYPE VARCHAR(50),
    UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED BOOLEAN DEFAULT FALSE,
    
    FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE(MESSAGE_ID) 
        ON DELETE CASCADE,
    
    INDEX idx_message_id (MESSAGE_ID),
    INDEX idx_upload_date (UPLOAD_DATE)
);

-- CHAT_MESSAGE 테이블에 MESSAGE_TYPE 컬럼 추가
ALTER TABLE CHAT_MESSAGE 
ADD COLUMN MESSAGE_TYPE VARCHAR(20) DEFAULT 'TEXT' COMMENT 'TEXT, IMAGE, FILE';

-- 기존 메시지들의 MESSAGE_TYPE을 TEXT로 설정
UPDATE CHAT_MESSAGE SET MESSAGE_TYPE = 'TEXT' WHERE MESSAGE_TYPE IS NULL;
